# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-httpd-service
spec:
  selector:
    app: my-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

